package gov.nih.nci.evs.compare.searchservice.util;

public class SemanticTypeWrapper {
	
	String[] SemanticTypes = {
			"propertyValue",
			"Conceptual Entity",
			"Amino Acid, Peptide, or Protein",
			"Pharmacologic Substance",
			"Therapeutic or Preventive Procedure",
			"Health Care Activity",
			"Finding",
			"Event",
			"Disease or Syndrome",
			"Temporal Concept",
			"Sign or Symptom",
			"Classification",
			"Functional Concept",
			"Intellectual Product",
			"Drug Delivery Device",
			"Neoplastic Process",
			"Quantitative Concept",
			"Human",
			"Body Location or Region",
			"Qualitative Concept",
			"Body Part, Organ, or Organ Component",
			"Organic Chemical",
			"Diagnostic Procedure",
			"Plant",
			"Medical Device",
			"Nucleic Acid, Nucleoside, or Nucleotide",
			"Cell",
			"Biomedical or Dental Material",
			"Laboratory Procedure",
			"Chemical Viewed Functionally",
			"Inorganic Chemical",
			"Spatial Concept",
			"Body Substance",
			"Clinical Attribute",
			"Congenital Abnormality",
			"Laboratory or Test Result",
			"Gene or Genome",
			"Immunologic Factor",
			"Enzyme",
			"Antibiotic",
			"Activity",
			"Indicator, Reagent, or Diagnostic Aid",
			"Idea or Concept",
			"Cell or Molecular Dysfunction",
			"Chemical Viewed Structurally",
			"Geographic Area",
			"Receptor",
			"Molecular Biology Research Technique",
			"Mental or Behavioral Dysfunction",
			"Food",
			"Biologically Active Substance",
			"Bacterium",
			"Research Activity",
			"Anatomical Structure",
			"Hazardous or Poisonous Substance",
			"Vitamin",
			"Professional or Occupational Group",
			"Health Care Related Organization",
			"Pathologic Function",
			"Virus",
			"Organism Attribute",
			"Body Space or Junction",
			"Manufactured Object",
			"Occupation or Discipline",
			"Group",
			"Substance",
			"Phenomenon or Process",
			"Governmental or Regulatory Activity",
			"Population Group",
			"Mental Process",
			"Hormone",
			"Daily or Recreational Activity",
			"Cell Component",
			"Genetic Function",
			"Biomedical Occupation or Discipline",
			"Chemical",
			"Mammal",
			"Natural Phenomenon or Process",
			"Group Attribute",
			"Organism",
			"Organism Function",
			"Organization",
			"Tissue",
			"Occupational Activity",
			"Physical Object",
			"Injury or Poisoning",
			"Fungus",
			"Cell Function",
			"Molecular Function",
			"Patient or Disabled Group",
			"Age Group",
			"Anatomical Abnormality",
			"Educational Activity",
			"Nucleotide Sequence",
			"Experimental Model of Disease",
			"Bird",
			"Physiologic Function",
			"Amino Acid Sequence",
			"Eukaryote",
			"Animal",
			"Body System",
			"Language",
			"Embryonic Structure",
			"Behavior",
			"Individual Behavior",
			"Element, Ion, or Isotope",
			"Organ or Tissue Function",
			"Acquired Abnormality",
			"Research Device",
			"Entity",
			"Amphibian",
			"Fish",
			"Machine Activity",
			"Vertebrate",
			"Molecular Sequence",
			"Social Behavior",
			"Human-caused Phenomenon or Process",
			"Regulation or Law",
			"Self-help or Relief Organization",
			"Biologic Function",
			"Neuroreactive Substance or Biogenic Amine",
			"Professional Society",
			"Family Group",
			"Steroid",
			"Organophosphorus Compound",
			"Environmental Effect of Humans",
			"Lipid",
			"Carbohydrate",
			"Clinical Drug"};

	public String[] getSemanticTypes() {
		return SemanticTypes;
	}

	public void setSemanticTypes(String[] semanticTypes) {
		SemanticTypes = semanticTypes;
	}

}
